server:
  port: 8080
  servlet:
    context-path: /user
spring:
  application:
    name: hh-user
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.30.133:9411/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka/

#启用feign的熔断器
feign:
  hystrix:
    enabled: true

#配置熔断连接超时时间
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000 #缺省为1000

#fegin连接超时时间
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000

#apollo
app:
  id: hh-user
apollo:
  meta: http://localhost:8080
  bootstarp:
    enabled: true
    eagerLoad:
      enabled: true
